if(EXISTS "/home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/systems/position_system/PositionSystemTest-b12d07c_tests.cmake")
  include("/home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/systems/position_system/PositionSystemTest-b12d07c_tests.cmake")
else()
  add_test(PositionSystemTest_NOT_BUILT-b12d07c PositionSystemTest_NOT_BUILT-b12d07c)
endif()
