if(EXISTS "/home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/systems/collision_system/CollisionSystemTest-b12d07c_tests.cmake")
  include("/home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/systems/collision_system/CollisionSystemTest-b12d07c_tests.cmake")
else()
  add_test(CollisionSystemTest_NOT_BUILT-b12d07c CollisionSystemTest_NOT_BUILT-b12d07c)
endif()
