add_test( [==[GameInstanceTest example]==] /home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/game/game_tests [==[GameInstanceTest example]==]  )
set_tests_properties( [==[GameInstanceTest example]==] PROPERTIES WORKING_DIRECTORY /home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/game)
add_test( [==[SystemManagerTest example]==] /home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/game/game_tests [==[SystemManagerTest example]==]  )
set_tests_properties( [==[SystemManagerTest example]==] PROPERTIES WORKING_DIRECTORY /home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/game)
add_test( [==[MapTest example]==] /home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/game/game_tests [==[MapTest example]==]  )
set_tests_properties( [==[MapTest example]==] PROPERTIES WORKING_DIRECTORY /home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/game)
add_test( [==[MapLoaderTest example]==] /home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/game/game_tests [==[MapLoaderTest example]==]  )
set_tests_properties( [==[MapLoaderTest example]==] PROPERTIES WORKING_DIRECTORY /home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/game)
add_test( [==[GameEventTest example]==] /home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/game/game_tests [==[GameEventTest example]==]  )
set_tests_properties( [==[GameEventTest example]==] PROPERTIES WORKING_DIRECTORY /home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/game)
set( game_tests_TESTS [==[GameInstanceTest example]==] [==[SystemManagerTest example]==] [==[MapTest example]==] [==[MapLoaderTest example]==] [==[GameEventTest example]==])
