if(EXISTS "/home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/systems/projectile_system/ProjectileSystemTest-b12d07c_tests.cmake")
  include("/home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/systems/projectile_system/ProjectileSystemTest-b12d07c_tests.cmake")
else()
  add_test(ProjectileSystemTest_NOT_BUILT-b12d07c ProjectileSystemTest_NOT_BUILT-b12d07c)
endif()
