# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nathan/Documents/epitech/tek3/cpp/repo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nathan/Documents/epitech/tek3/cpp/repo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/nathan/Documents/epitech/tek3/cpp/repo/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"bin\" \"devel\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nathan/Documents/epitech/tek3/cpp/repo/CMakeFiles /home/nathan/Documents/epitech/tek3/cpp/repo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nathan/Documents/epitech/tek3/cpp/repo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named fclean

# Build rule for target.
fclean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fclean
.PHONY : fclean

# fast build rule for target.
fclean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fclean.dir/build.make CMakeFiles/fclean.dir/build
.PHONY : fclean/fast

#=============================================================================
# Target rules for targets named re

# Build rule for target.
re: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 re
.PHONY : re

# fast build rule for target.
re/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/re.dir/build.make CMakeFiles/re.dir/build
.PHONY : re/fast

#=============================================================================
# Target rules for targets named sfml-system

# Build rule for target.
sfml-system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-system
.PHONY : sfml-system

# fast build rule for target.
sfml-system/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/System/CMakeFiles/sfml-system.dir/build.make _deps/sfml-build/src/SFML/System/CMakeFiles/sfml-system.dir/build
.PHONY : sfml-system/fast

#=============================================================================
# Target rules for targets named sfml-window

# Build rule for target.
sfml-window: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-window
.PHONY : sfml-window

# fast build rule for target.
sfml-window/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Window/CMakeFiles/sfml-window.dir/build.make _deps/sfml-build/src/SFML/Window/CMakeFiles/sfml-window.dir/build
.PHONY : sfml-window/fast

#=============================================================================
# Target rules for targets named sfml-network

# Build rule for target.
sfml-network: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-network
.PHONY : sfml-network

# fast build rule for target.
sfml-network/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Network/CMakeFiles/sfml-network.dir/build.make _deps/sfml-build/src/SFML/Network/CMakeFiles/sfml-network.dir/build
.PHONY : sfml-network/fast

#=============================================================================
# Target rules for targets named sfml-graphics

# Build rule for target.
sfml-graphics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-graphics
.PHONY : sfml-graphics

# fast build rule for target.
sfml-graphics/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build.make _deps/sfml-build/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build
.PHONY : sfml-graphics/fast

#=============================================================================
# Target rules for targets named sfml-audio

# Build rule for target.
sfml-audio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-audio
.PHONY : sfml-audio

# fast build rule for target.
sfml-audio/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Audio/CMakeFiles/sfml-audio.dir/build.make _deps/sfml-build/src/SFML/Audio/CMakeFiles/sfml-audio.dir/build
.PHONY : sfml-audio/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

#=============================================================================
# Target rules for targets named project_clean

# Build rule for target.
project_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project_clean
.PHONY : project_clean

# fast build rule for target.
project_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/CMakeFiles/project_clean.dir/build.make project/CMakeFiles/project_clean.dir/build
.PHONY : project_clean/fast

#=============================================================================
# Target rules for targets named engine_clean

# Build rule for target.
engine_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine_clean
.PHONY : engine_clean

# fast build rule for target.
engine_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/CMakeFiles/engine_clean.dir/build.make project/engine/CMakeFiles/engine_clean.dir/build
.PHONY : engine_clean/fast

#=============================================================================
# Target rules for targets named component_clean

# Build rule for target.
component_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 component_clean
.PHONY : component_clean

# fast build rule for target.
component_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/components/CMakeFiles/component_clean.dir/build.make project/engine/components/CMakeFiles/component_clean.dir/build
.PHONY : component_clean/fast

#=============================================================================
# Target rules for targets named ecs

# Build rule for target.
ecs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ecs
.PHONY : ecs

# fast build rule for target.
ecs/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/ecs/CMakeFiles/ecs.dir/build.make project/engine/ecs/CMakeFiles/ecs.dir/build
.PHONY : ecs/fast

#=============================================================================
# Target rules for targets named ecs_tests

# Build rule for target.
ecs_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ecs_tests
.PHONY : ecs_tests

# fast build rule for target.
ecs_tests/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/ecs/CMakeFiles/ecs_tests.dir/build.make project/engine/ecs/CMakeFiles/ecs_tests.dir/build
.PHONY : ecs_tests/fast

#=============================================================================
# Target rules for targets named ecs_clean

# Build rule for target.
ecs_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ecs_clean
.PHONY : ecs_clean

# fast build rule for target.
ecs_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/ecs/CMakeFiles/ecs_clean.dir/build.make project/engine/ecs/CMakeFiles/ecs_clean.dir/build
.PHONY : ecs_clean/fast

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/game/CMakeFiles/game.dir/build.make project/engine/game/CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named game_tests

# Build rule for target.
game_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game_tests
.PHONY : game_tests

# fast build rule for target.
game_tests/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/game/CMakeFiles/game_tests.dir/build.make project/engine/game/CMakeFiles/game_tests.dir/build
.PHONY : game_tests/fast

#=============================================================================
# Target rules for targets named game_clean

# Build rule for target.
game_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game_clean
.PHONY : game_clean

# fast build rule for target.
game_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/game/CMakeFiles/game_clean.dir/build.make project/engine/game/CMakeFiles/game_clean.dir/build
.PHONY : game_clean/fast

#=============================================================================
# Target rules for targets named network

# Build rule for target.
network: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 network
.PHONY : network

# fast build rule for target.
network/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/network/CMakeFiles/network.dir/build.make project/engine/network/CMakeFiles/network.dir/build
.PHONY : network/fast

#=============================================================================
# Target rules for targets named network_tests

# Build rule for target.
network_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 network_tests
.PHONY : network_tests

# fast build rule for target.
network_tests/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/network/CMakeFiles/network_tests.dir/build.make project/engine/network/CMakeFiles/network_tests.dir/build
.PHONY : network_tests/fast

#=============================================================================
# Target rules for targets named network_clean

# Build rule for target.
network_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 network_clean
.PHONY : network_clean

# fast build rule for target.
network_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/network/CMakeFiles/network_clean.dir/build.make project/engine/network/CMakeFiles/network_clean.dir/build
.PHONY : network_clean/fast

#=============================================================================
# Target rules for targets named system_clean

# Build rule for target.
system_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 system_clean
.PHONY : system_clean

# fast build rule for target.
system_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/CMakeFiles/system_clean.dir/build.make project/engine/systems/CMakeFiles/system_clean.dir/build
.PHONY : system_clean/fast

#=============================================================================
# Target rules for targets named PositionSystem

# Build rule for target.
PositionSystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PositionSystem
.PHONY : PositionSystem

# fast build rule for target.
PositionSystem/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/position_system/CMakeFiles/PositionSystem.dir/build.make project/engine/systems/position_system/CMakeFiles/PositionSystem.dir/build
.PHONY : PositionSystem/fast

#=============================================================================
# Target rules for targets named PositionSystemTest

# Build rule for target.
PositionSystemTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PositionSystemTest
.PHONY : PositionSystemTest

# fast build rule for target.
PositionSystemTest/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/position_system/CMakeFiles/PositionSystemTest.dir/build.make project/engine/systems/position_system/CMakeFiles/PositionSystemTest.dir/build
.PHONY : PositionSystemTest/fast

#=============================================================================
# Target rules for targets named PositionSystem_clean

# Build rule for target.
PositionSystem_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PositionSystem_clean
.PHONY : PositionSystem_clean

# fast build rule for target.
PositionSystem_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/position_system/CMakeFiles/PositionSystem_clean.dir/build.make project/engine/systems/position_system/CMakeFiles/PositionSystem_clean.dir/build
.PHONY : PositionSystem_clean/fast

#=============================================================================
# Target rules for targets named ControlSystem

# Build rule for target.
ControlSystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ControlSystem
.PHONY : ControlSystem

# fast build rule for target.
ControlSystem/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/control_system/CMakeFiles/ControlSystem.dir/build.make project/engine/systems/control_system/CMakeFiles/ControlSystem.dir/build
.PHONY : ControlSystem/fast

#=============================================================================
# Target rules for targets named ControlSystemTest

# Build rule for target.
ControlSystemTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ControlSystemTest
.PHONY : ControlSystemTest

# fast build rule for target.
ControlSystemTest/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/control_system/CMakeFiles/ControlSystemTest.dir/build.make project/engine/systems/control_system/CMakeFiles/ControlSystemTest.dir/build
.PHONY : ControlSystemTest/fast

#=============================================================================
# Target rules for targets named ControlSystem_clean

# Build rule for target.
ControlSystem_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ControlSystem_clean
.PHONY : ControlSystem_clean

# fast build rule for target.
ControlSystem_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/control_system/CMakeFiles/ControlSystem_clean.dir/build.make project/engine/systems/control_system/CMakeFiles/ControlSystem_clean.dir/build
.PHONY : ControlSystem_clean/fast

#=============================================================================
# Target rules for targets named CollisionSystem

# Build rule for target.
CollisionSystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CollisionSystem
.PHONY : CollisionSystem

# fast build rule for target.
CollisionSystem/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/collision_system/CMakeFiles/CollisionSystem.dir/build.make project/engine/systems/collision_system/CMakeFiles/CollisionSystem.dir/build
.PHONY : CollisionSystem/fast

#=============================================================================
# Target rules for targets named CollisionSystemTest

# Build rule for target.
CollisionSystemTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CollisionSystemTest
.PHONY : CollisionSystemTest

# fast build rule for target.
CollisionSystemTest/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/collision_system/CMakeFiles/CollisionSystemTest.dir/build.make project/engine/systems/collision_system/CMakeFiles/CollisionSystemTest.dir/build
.PHONY : CollisionSystemTest/fast

#=============================================================================
# Target rules for targets named CollisionSystem_clean

# Build rule for target.
CollisionSystem_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CollisionSystem_clean
.PHONY : CollisionSystem_clean

# fast build rule for target.
CollisionSystem_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/collision_system/CMakeFiles/CollisionSystem_clean.dir/build.make project/engine/systems/collision_system/CMakeFiles/CollisionSystem_clean.dir/build
.PHONY : CollisionSystem_clean/fast

#=============================================================================
# Target rules for targets named PhysicsSystem

# Build rule for target.
PhysicsSystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PhysicsSystem
.PHONY : PhysicsSystem

# fast build rule for target.
PhysicsSystem/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/physics_system/CMakeFiles/PhysicsSystem.dir/build.make project/engine/systems/physics_system/CMakeFiles/PhysicsSystem.dir/build
.PHONY : PhysicsSystem/fast

#=============================================================================
# Target rules for targets named PhysicsSystemTest

# Build rule for target.
PhysicsSystemTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PhysicsSystemTest
.PHONY : PhysicsSystemTest

# fast build rule for target.
PhysicsSystemTest/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/physics_system/CMakeFiles/PhysicsSystemTest.dir/build.make project/engine/systems/physics_system/CMakeFiles/PhysicsSystemTest.dir/build
.PHONY : PhysicsSystemTest/fast

#=============================================================================
# Target rules for targets named PhysicsSystem_clean

# Build rule for target.
PhysicsSystem_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PhysicsSystem_clean
.PHONY : PhysicsSystem_clean

# fast build rule for target.
PhysicsSystem_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/physics_system/CMakeFiles/PhysicsSystem_clean.dir/build.make project/engine/systems/physics_system/CMakeFiles/PhysicsSystem_clean.dir/build
.PHONY : PhysicsSystem_clean/fast

#=============================================================================
# Target rules for targets named AISystem

# Build rule for target.
AISystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AISystem
.PHONY : AISystem

# fast build rule for target.
AISystem/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/ai_system/CMakeFiles/AISystem.dir/build.make project/engine/systems/ai_system/CMakeFiles/AISystem.dir/build
.PHONY : AISystem/fast

#=============================================================================
# Target rules for targets named AISystemTest

# Build rule for target.
AISystemTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AISystemTest
.PHONY : AISystemTest

# fast build rule for target.
AISystemTest/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/ai_system/CMakeFiles/AISystemTest.dir/build.make project/engine/systems/ai_system/CMakeFiles/AISystemTest.dir/build
.PHONY : AISystemTest/fast

#=============================================================================
# Target rules for targets named AISystem_clean

# Build rule for target.
AISystem_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AISystem_clean
.PHONY : AISystem_clean

# fast build rule for target.
AISystem_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/ai_system/CMakeFiles/AISystem_clean.dir/build.make project/engine/systems/ai_system/CMakeFiles/AISystem_clean.dir/build
.PHONY : AISystem_clean/fast

#=============================================================================
# Target rules for targets named ProjectileSystem

# Build rule for target.
ProjectileSystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ProjectileSystem
.PHONY : ProjectileSystem

# fast build rule for target.
ProjectileSystem/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/projectile_system/CMakeFiles/ProjectileSystem.dir/build.make project/engine/systems/projectile_system/CMakeFiles/ProjectileSystem.dir/build
.PHONY : ProjectileSystem/fast

#=============================================================================
# Target rules for targets named ProjectileSystemTest

# Build rule for target.
ProjectileSystemTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ProjectileSystemTest
.PHONY : ProjectileSystemTest

# fast build rule for target.
ProjectileSystemTest/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/projectile_system/CMakeFiles/ProjectileSystemTest.dir/build.make project/engine/systems/projectile_system/CMakeFiles/ProjectileSystemTest.dir/build
.PHONY : ProjectileSystemTest/fast

#=============================================================================
# Target rules for targets named ProjectileSystem_clean

# Build rule for target.
ProjectileSystem_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ProjectileSystem_clean
.PHONY : ProjectileSystem_clean

# fast build rule for target.
ProjectileSystem_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/projectile_system/CMakeFiles/ProjectileSystem_clean.dir/build.make project/engine/systems/projectile_system/CMakeFiles/ProjectileSystem_clean.dir/build
.PHONY : ProjectileSystem_clean/fast

#=============================================================================
# Target rules for targets named RenderSystem

# Build rule for target.
RenderSystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RenderSystem
.PHONY : RenderSystem

# fast build rule for target.
RenderSystem/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/render_system/CMakeFiles/RenderSystem.dir/build.make project/engine/systems/render_system/CMakeFiles/RenderSystem.dir/build
.PHONY : RenderSystem/fast

#=============================================================================
# Target rules for targets named RenderSystemTest

# Build rule for target.
RenderSystemTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RenderSystemTest
.PHONY : RenderSystemTest

# fast build rule for target.
RenderSystemTest/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/render_system/CMakeFiles/RenderSystemTest.dir/build.make project/engine/systems/render_system/CMakeFiles/RenderSystemTest.dir/build
.PHONY : RenderSystemTest/fast

#=============================================================================
# Target rules for targets named RenderSystem_clean

# Build rule for target.
RenderSystem_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RenderSystem_clean
.PHONY : RenderSystem_clean

# fast build rule for target.
RenderSystem_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/render_system/CMakeFiles/RenderSystem_clean.dir/build.make project/engine/systems/render_system/CMakeFiles/RenderSystem_clean.dir/build
.PHONY : RenderSystem_clean/fast

#=============================================================================
# Target rules for targets named SoundSystem

# Build rule for target.
SoundSystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SoundSystem
.PHONY : SoundSystem

# fast build rule for target.
SoundSystem/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/sound_system/CMakeFiles/SoundSystem.dir/build.make project/engine/systems/sound_system/CMakeFiles/SoundSystem.dir/build
.PHONY : SoundSystem/fast

#=============================================================================
# Target rules for targets named SoundSystemTest

# Build rule for target.
SoundSystemTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SoundSystemTest
.PHONY : SoundSystemTest

# fast build rule for target.
SoundSystemTest/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/sound_system/CMakeFiles/SoundSystemTest.dir/build.make project/engine/systems/sound_system/CMakeFiles/SoundSystemTest.dir/build
.PHONY : SoundSystemTest/fast

#=============================================================================
# Target rules for targets named SoundSystem_clean

# Build rule for target.
SoundSystem_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SoundSystem_clean
.PHONY : SoundSystem_clean

# fast build rule for target.
SoundSystem_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/sound_system/CMakeFiles/SoundSystem_clean.dir/build.make project/engine/systems/sound_system/CMakeFiles/SoundSystem_clean.dir/build
.PHONY : SoundSystem_clean/fast

#=============================================================================
# Target rules for targets named CleanupSystem

# Build rule for target.
CleanupSystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CleanupSystem
.PHONY : CleanupSystem

# fast build rule for target.
CleanupSystem/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/cleanup_system/CMakeFiles/CleanupSystem.dir/build.make project/engine/systems/cleanup_system/CMakeFiles/CleanupSystem.dir/build
.PHONY : CleanupSystem/fast

#=============================================================================
# Target rules for targets named CleanupSystemTest

# Build rule for target.
CleanupSystemTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CleanupSystemTest
.PHONY : CleanupSystemTest

# fast build rule for target.
CleanupSystemTest/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/cleanup_system/CMakeFiles/CleanupSystemTest.dir/build.make project/engine/systems/cleanup_system/CMakeFiles/CleanupSystemTest.dir/build
.PHONY : CleanupSystemTest/fast

#=============================================================================
# Target rules for targets named CleanupSystem_clean

# Build rule for target.
CleanupSystem_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CleanupSystem_clean
.PHONY : CleanupSystem_clean

# fast build rule for target.
CleanupSystem_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/cleanup_system/CMakeFiles/CleanupSystem_clean.dir/build.make project/engine/systems/cleanup_system/CMakeFiles/CleanupSystem_clean.dir/build
.PHONY : CleanupSystem_clean/fast

#=============================================================================
# Target rules for targets named SpawnSystem

# Build rule for target.
SpawnSystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SpawnSystem
.PHONY : SpawnSystem

# fast build rule for target.
SpawnSystem/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/spawn_system/CMakeFiles/SpawnSystem.dir/build.make project/engine/systems/spawn_system/CMakeFiles/SpawnSystem.dir/build
.PHONY : SpawnSystem/fast

#=============================================================================
# Target rules for targets named SpawnSystemTest

# Build rule for target.
SpawnSystemTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SpawnSystemTest
.PHONY : SpawnSystemTest

# fast build rule for target.
SpawnSystemTest/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/spawn_system/CMakeFiles/SpawnSystemTest.dir/build.make project/engine/systems/spawn_system/CMakeFiles/SpawnSystemTest.dir/build
.PHONY : SpawnSystemTest/fast

#=============================================================================
# Target rules for targets named SpawnSystem_clean

# Build rule for target.
SpawnSystem_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SpawnSystem_clean
.PHONY : SpawnSystem_clean

# fast build rule for target.
SpawnSystem_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/systems/spawn_system/CMakeFiles/SpawnSystem_clean.dir/build.make project/engine/systems/spawn_system/CMakeFiles/SpawnSystem_clean.dir/build
.PHONY : SpawnSystem_clean/fast

#=============================================================================
# Target rules for targets named tools

# Build rule for target.
tools: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tools
.PHONY : tools

# fast build rule for target.
tools/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/tools/CMakeFiles/tools.dir/build.make project/engine/tools/CMakeFiles/tools.dir/build
.PHONY : tools/fast

#=============================================================================
# Target rules for targets named tools_tests

# Build rule for target.
tools_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tools_tests
.PHONY : tools_tests

# fast build rule for target.
tools_tests/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/tools/CMakeFiles/tools_tests.dir/build.make project/engine/tools/CMakeFiles/tools_tests.dir/build
.PHONY : tools_tests/fast

#=============================================================================
# Target rules for targets named tools_clean

# Build rule for target.
tools_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tools_clean
.PHONY : tools_clean

# fast build rule for target.
tools_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/engine/tools/CMakeFiles/tools_clean.dir/build.make project/engine/tools/CMakeFiles/tools_clean.dir/build
.PHONY : tools_clean/fast

#=============================================================================
# Target rules for targets named server_lib

# Build rule for target.
server_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server_lib
.PHONY : server_lib

# fast build rule for target.
server_lib/fast:
	$(MAKE) $(MAKESILENT) -f project/server/CMakeFiles/server_lib.dir/build.make project/server/CMakeFiles/server_lib.dir/build
.PHONY : server_lib/fast

#=============================================================================
# Target rules for targets named r-type_server

# Build rule for target.
r-type_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r-type_server
.PHONY : r-type_server

# fast build rule for target.
r-type_server/fast:
	$(MAKE) $(MAKESILENT) -f project/server/CMakeFiles/r-type_server.dir/build.make project/server/CMakeFiles/r-type_server.dir/build
.PHONY : r-type_server/fast

#=============================================================================
# Target rules for targets named server_tests

# Build rule for target.
server_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server_tests
.PHONY : server_tests

# fast build rule for target.
server_tests/fast:
	$(MAKE) $(MAKESILENT) -f project/server/CMakeFiles/server_tests.dir/build.make project/server/CMakeFiles/server_tests.dir/build
.PHONY : server_tests/fast

#=============================================================================
# Target rules for targets named server_clean

# Build rule for target.
server_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server_clean
.PHONY : server_clean

# fast build rule for target.
server_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/server/CMakeFiles/server_clean.dir/build.make project/server/CMakeFiles/server_clean.dir/build
.PHONY : server_clean/fast

#=============================================================================
# Target rules for targets named client_lib

# Build rule for target.
client_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client_lib
.PHONY : client_lib

# fast build rule for target.
client_lib/fast:
	$(MAKE) $(MAKESILENT) -f project/client/CMakeFiles/client_lib.dir/build.make project/client/CMakeFiles/client_lib.dir/build
.PHONY : client_lib/fast

#=============================================================================
# Target rules for targets named r-type_client

# Build rule for target.
r-type_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r-type_client
.PHONY : r-type_client

# fast build rule for target.
r-type_client/fast:
	$(MAKE) $(MAKESILENT) -f project/client/CMakeFiles/r-type_client.dir/build.make project/client/CMakeFiles/r-type_client.dir/build
.PHONY : r-type_client/fast

#=============================================================================
# Target rules for targets named client_tests

# Build rule for target.
client_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client_tests
.PHONY : client_tests

# fast build rule for target.
client_tests/fast:
	$(MAKE) $(MAKESILENT) -f project/client/CMakeFiles/client_tests.dir/build.make project/client/CMakeFiles/client_tests.dir/build
.PHONY : client_tests/fast

#=============================================================================
# Target rules for targets named client_clean

# Build rule for target.
client_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client_clean
.PHONY : client_clean

# fast build rule for target.
client_clean/fast:
	$(MAKE) $(MAKESILENT) -f project/client/CMakeFiles/client_clean.dir/build.make project/client/CMakeFiles/client_clean.dir/build
.PHONY : client_clean/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... AISystem_clean"
	@echo "... CleanupSystem_clean"
	@echo "... CollisionSystem_clean"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... ControlSystem_clean"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... PhysicsSystem_clean"
	@echo "... PositionSystem_clean"
	@echo "... ProjectileSystem_clean"
	@echo "... RenderSystem_clean"
	@echo "... SoundSystem_clean"
	@echo "... SpawnSystem_clean"
	@echo "... client_clean"
	@echo "... component_clean"
	@echo "... ecs_clean"
	@echo "... engine_clean"
	@echo "... fclean"
	@echo "... game_clean"
	@echo "... network_clean"
	@echo "... project_clean"
	@echo "... re"
	@echo "... server_clean"
	@echo "... system_clean"
	@echo "... tools_clean"
	@echo "... AISystem"
	@echo "... AISystemTest"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... CleanupSystem"
	@echo "... CleanupSystemTest"
	@echo "... CollisionSystem"
	@echo "... CollisionSystemTest"
	@echo "... ControlSystem"
	@echo "... ControlSystemTest"
	@echo "... PhysicsSystem"
	@echo "... PhysicsSystemTest"
	@echo "... PositionSystem"
	@echo "... PositionSystemTest"
	@echo "... ProjectileSystem"
	@echo "... ProjectileSystemTest"
	@echo "... RenderSystem"
	@echo "... RenderSystemTest"
	@echo "... SoundSystem"
	@echo "... SoundSystemTest"
	@echo "... SpawnSystem"
	@echo "... SpawnSystemTest"
	@echo "... client_lib"
	@echo "... client_tests"
	@echo "... ecs"
	@echo "... ecs_tests"
	@echo "... game"
	@echo "... game_tests"
	@echo "... network"
	@echo "... network_tests"
	@echo "... r-type_client"
	@echo "... r-type_server"
	@echo "... server_lib"
	@echo "... server_tests"
	@echo "... sfml-audio"
	@echo "... sfml-graphics"
	@echo "... sfml-network"
	@echo "... sfml-system"
	@echo "... sfml-window"
	@echo "... tools"
	@echo "... tools_tests"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

