if(EXISTS "/home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/systems/render_system/RenderSystemTest-b12d07c_tests.cmake")
  include("/home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/systems/render_system/RenderSystemTest-b12d07c_tests.cmake")
else()
  add_test(RenderSystemTest_NOT_BUILT-b12d07c RenderSystemTest_NOT_BUILT-b12d07c)
endif()
