if(EXISTS "/home/nathan/Documents/epitech/tek3/cpp/repo/project/server/server_tests-b12d07c_tests.cmake")
  include("/home/nathan/Documents/epitech/tek3/cpp/repo/project/server/server_tests-b12d07c_tests.cmake")
else()
  add_test(server_tests_NOT_BUILT-b12d07c server_tests_NOT_BUILT-b12d07c)
endif()
