if(EXISTS "/home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/systems/physics_system/PhysicsSystemTest-b12d07c_tests.cmake")
  include("/home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/systems/physics_system/PhysicsSystemTest-b12d07c_tests.cmake")
else()
  add_test(PhysicsSystemTest_NOT_BUILT-b12d07c PhysicsSystemTest_NOT_BUILT-b12d07c)
endif()
