if(EXISTS "/home/alpharone/tec3/oop/origine/G-CPP-500-PAR-5-1-rtype-4/project/engine/systems/animation_system/AnimationSystemTest-b12d07c_tests.cmake")
  include("/home/alpharone/tec3/oop/origine/G-CPP-500-PAR-5-1-rtype-4/project/engine/systems/animation_system/AnimationSystemTest-b12d07c_tests.cmake")
else()
  add_test(AnimationSystemTest_NOT_BUILT-b12d07c AnimationSystemTest_NOT_BUILT-b12d07c)
endif()
