if(EXISTS "/home/nathan/Documents/epitech/tek3/cpp/repo/project/client/client_tests-b12d07c_tests.cmake")
  include("/home/nathan/Documents/epitech/tek3/cpp/repo/project/client/client_tests-b12d07c_tests.cmake")
else()
  add_test(client_tests_NOT_BUILT-b12d07c client_tests_NOT_BUILT-b12d07c)
endif()
