if(EXISTS "/home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/systems/ai_system/AISystemTest-b12d07c_tests.cmake")
  include("/home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/systems/ai_system/AISystemTest-b12d07c_tests.cmake")
else()
  add_test(AISystemTest_NOT_BUILT-b12d07c AISystemTest_NOT_BUILT-b12d07c)
endif()
