if(EXISTS "/home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/tools/tools_tests-b12d07c_tests.cmake")
  include("/home/nathan/Documents/epitech/tek3/cpp/repo/project/engine/tools/tools_tests-b12d07c_tests.cmake")
else()
  add_test(tools_tests_NOT_BUILT-b12d07c tools_tests_NOT_BUILT-b12d07c)
endif()
